services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUN_ENV: development
    init: true
    volumes:
      - .:/app
    environment:
      PORT: 5000
      RUN_ENV: development
    ports:
      - "5000:5000"

volumes:
  data:
    driver: local