from . import calculo_quinta_peru, consolidacion_compras_por_estilo, devoluciones_api_mercado_pago, blue_express, example

programs = dict(calculo_quinta_peru=calculo_quinta_peru, consolidacion_compras_por_estilo=consolidacion_compras_por_estilo, devoluciones_api_mercado_pago=devoluciones_api_mercado_pago, blue_express=blue_express, example=example)
