name: staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY:latest --build-arg RUN_ENV=staging .
        env:
          ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.APPLICATION_NAME }}

      - name: Push Docker image to Amazon ECR
        run: docker push $ECR_REPOSITORY:latest
        env:
          ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.APPLICATION_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: worker-staging
          version_label: ${{ secrets.APPLICATION_NAME }}-latest
